<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<?php if (isset($accessDenied)) { ?>
    <div class="text-center">
        <h4><?php echo $accessDenied?></h4>
    </div>
    <?php die(); } ?>

<?php if (isset($result)) { ?>
    <div class="text-center">
        <h4><?php echo $result?></h4>
    </div>
<?php  } ?>

<form method="post" class="form-inline" action="/admin/editCategory/category=<?php echo $id ?>">

    <div class="form-inline">
        <label class="col-sm-2 control-label">Название категории:</label>
        <div class="col-sm-5">
            <input name="name" type="text" class="form-control" value="<?php echo $category['name'] ?>">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Редактировать</button>
        </div>
    </div>
</form>
</body>
</html>