<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<?php if (isset($accessDenied)) { ?>
    <div class="text-center">
        <h4><?php echo $accessDenied?></h4>
    </div>
<?php die(); } ?>

<?php if (isset($users)) { ?>

        <table class="table table-striped">
            <tr>
                <th>id</th>
                <th>name</th>
                <th>surname</th>
                <th>login</th>
                <th>email</th>
                <th>Удалить</th>
                <th>Дать привилегии</th>
            </tr>

                <?php foreach ($users as $user) { ?>
                    <tr>
                        <td><?php echo $user['id'] ?></td>
                        <td><?php echo $user['name'] ?></td>
                        <td><?php echo $user['surname'] ?></td>
                        <td><?php echo $user['login'] ?></td>
                        <td><?php echo $user['email'] ?></td>
                        <td><a href="/admin/deleteUser/user=<?php echo $user['id'] ?>" class="btn btn-primary" role="button">Удалить</a></td>
                        <?php if($user['isAdmin'] == 0){ ?>
                        <td><a href="/admin/giveAdmin/user=<?php echo $user['id'] ?>" class="btn btn-primary" role="button">Дать админа</a></td>
                        <?php } else { ?>
                            <td><a href="/admin/takeAdmin/user=<?php echo $user['id'] ?>" class="btn btn-primary" role="button">Забрать админа</a></td>
                       <?php } ?>
                    </tr>
                <?php } ?>

        </table>

    <div class="text-center">
        <nav>
            <ul class="pagination">

                <?php if ($pages['first'] != null) { ?>
                    <li><a href="/post/page=<?php echo $pages['first'] ?>">Первая</a></li>
               <?php } ?>

                <?php if ($pages['pre'] != null) { ?>
                   <li><a href="<?php echo $link . $pages['pre'] ?>"><?php echo $pages['pre'] ?></a></li>
                <?php } ?>

                <?php if ($pages['cur'] != null) { ?>
                   <li><a class="active btn-primary"
                       href="<?php echo $link . $pages['cur'] ?>"><?php echo $pages['cur'] ?></a></li>
                <?php } ?>

                <?php if ($pages['next'] != null) { ?>
                 <li><a href="<?php echo $link . $pages['next'] ?>"><?php echo $pages['next'] ?></a></li>
                <?php } ?>

                <?php if ($pages['last'] != null) { ?>
                 <li><a href="<?php echo $link . $pages['last'] ?>">Последняя</a></li>
                <?php } ?>
            </ul>
        </nav>
    </div>

<?php } else { ?>
                <div class="text-center">
                    <h4>Пользователей не найдено</h4>
                </div>
<?php } ?>


</body>
</html>