<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="resume">
<img class="img-rounded" id="resume" src="../images/resume.bmp">
    <div class="text-center">
        <h2>Джим Максим</h2>
        <table id="table" class="table">
            <tr>
                <td><b>Email</b>
                <td>maximjim94@gmail.com</td>
            </tr>
            <tr>
                <td><b>Skype</b>
                <td>maxjim94</td>
            </tr>
            <tr>
                <td><b>Телефон</b>
                <td>+38(093)-476-01-82</td>
            </tr>
            <tr>
                <td><b>LinkedIN</b>
                <td>https://www.linkedin.com/in/maksym-dzhym-a73375118</td>
            </tr>
        </table>
    </div>

    <p><b><ins class="myheader">Основные знания и навыки:</ins></b></p>
    <ul class="mylist">
        <li><b>Back-End:</b> PHP – хорошо пониманию ООП, паттерн MVC;</li>
        <li><b>Front-End:</b>HTML, CSS, JavaScript - AJAX, jQuery, BootStrap3 -  в процессе изучения;</li>
        <li><b>Базы данных: </b> MySqL – проектировка базы, написание запросов, PHPMyAdmin;</li>
        <li><b>OC:</b>Windows, MacOS;</li>
        <li><b>Другое:</b>Владею навыками работы с сервисами контроля версий (в частности GitHub).</li>
    </ul>

    <p class="myparag">Все мои проекты можно найти <a  href="https://github.com/maximjim">здесь</a>. </p>

    <p class="myparag">
        В данный момент работаю над диплом проектом в PHP-academy.
        Это будет новостной сайт о туризме, с различными возможностями как для
        администратора так и для пользователей.
        Который находится здесь, это только тестовая версия, которая просит еще много доработок:
        <a  href="https://github.com/maximjim/express-news">туц-туц))</a>.
    </p>

    <p><b><ins class="myheader">Мне нравится:</ins></b></p>
    <ul class="mylist">
        <li>Писать красивый и понятный код, писать много кода, мне это очень нравится;</li>
        <li>Обожаю решать сложные задачи, с которыми раньше не сталкивался;</li>
        <li>Общаться с единомышленниками, которые могут подтолкнуть в нужном направлении в момент остановки решения какого либо задания;</li>
        <li>Работать в команде с более сильными программистами (чтобы было на кого равняться, перенимать опыт и развиваться самому).</li>
    </ul>

    <p><b><ins class="myheader">Планиурю:</ins></b></p>
    <ul class="mylist">
        <li>Повысить свой уровень английского до Upper-intermediate;</li>
        <li>Достичь уровня Middle PHP, а далее и Senior PHP;</li>
        <li>Постоянно работать над собой и развиваться;</li>
        <li>Освоить как можно больше фреймворков, такие как Symfony, Zend, Yii.</li>
    </ul>

    <p><b><ins class="myheader">Мои пожелания относительно работы:</ins></b></p>
    <ul class="mylist">
        <li>
            Зарабатывать 300-500 $ во время стажировки и испытательного срока,
            с дальнейшей возможностью пересмотра заработной платы с ростом моих навыков;
        </li>
        <li>Работать Full Time</li>
        <li><b>В случае необходимости я могу:</b></li>
        <li>Помочь другому сотруднику выполнить задачу,если горит дедлайн и релиз близко</li>
    </ul>

    <p><b><ins class="myheader">Образование:</ins></b></p>
    <ul class="mylist">
        <li>
            <b>Черниговский национальный технологический университет</b> –
            специальность «Компьютерная инженерия» заочно 2012-2017;
        </li>
        <li>
            <b>Школа веб-программирования  PHP-academy - </b>
            2016 ( Киев), изучал такие технологии как: HTML, CSS, MySqL, PHP(OOP, MVC), Symfony2.
        </li>
        <li>
            Самостоятельное изучение технологий изучающих в академии,
            также различных CMS систем, таких как WordPress, Joomla, OpenCart.
        </li>
    </ul>

</div>
</body>
</html>