<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="text-center">
        <h2>Мои контакты:</h2>
        <table class="table">
            <tr>
                <td><b>Email</b>
                <td>maximjim94@gmail.com</td>
            </tr>
            <tr>
                <td><b>Skype</b>
                <td>maxjim94</td>
            </tr>
            <tr>
                <td><b>Телефон</b>
                <td>+38(093)-476-01-82</td>
            </tr>
            <tr>
                <td><b>LinkedIN</b>
                <td>https://www.linkedin.com/in/maksym-dzhym-a73375118</td>
            </tr>
        </table>
</div>

<div>
    <p class="mylist">Также вы можете написать нам письмо воспользовавшись
        <a id="btn" class="btn-primary" href="/contact/#">формой обратной связи</a></p>

</div>
</body>
</html>