<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<!-- footer -->
<div class="panel panel-default">
    <div class="panel-footer panel-body navbar-brand">
        <h3>Copyright Maksym Dzhym</h3>
        <h4>Все права защищены</h4>
        <h4> Поблагодарить разработчика вы можете в этом разделе, просто посмотрите <a href="/#">рекламу</a> </h4>
    </div>
</div>

</body>
</html>