<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>


<!-- post -->
<div class=" center-block text-center">
    <div class="col-md-8">
        <?php if (!empty($posts)) {
            foreach ($posts as $post) { ?>
                <div class="thumbnail">
                    <h3> <?php echo $post['name'] ?></h3>


                    <div class="row table">
                        <div class="col-sm-6 col-md-6">
                            <a href="/region=<?php echo $post['region']['id'] ?>">
                                <h3><?php echo $post['region']['name'] ?></h3></a>
                            <h4>Автор: <a
                                    href="/post/user=<?php echo $post['author']['id'] ?>"><?php echo $post['author']['login'] ?> </a>
                            </h4>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <a href="#"><h3>Комментариев<span class="badge"><?php echo $post['commentCnt'] ?></span>
                                </h3></a>
                            <h6> Дата добавления: <?php echo $post['created'] ?></h6>

                        </div>
                    </div>


                    <img src="../images/<?php echo $post['image'] ?>" alt="131">
                    <div class="caption">

                        <p> <?php echo substr($post['content'], 0, 325) . "..." ?></p>
                        <p><a href="/post/<?php echo $post['id'] ?>" class="btn btn-primary" role="button">Читать
                                полностью</a>
                            <?php if (isset($_SESSION['user']) and $_SESSION['user']['isAdmin'] == 1){ ?>
                        <p><a href="/admin/deletePost/post=<?php echo $post['id'] ?>" class="btn btn-primary"
                              role="button">Удалить пост</a>

                        <p><a href="/admin/editPost/post=<?php echo $post['id'] ?>" class="btn btn-primary"
                              role="button">Редактировать пост</a>
                            <?php } ?>
                    </div>
                </div>
            <?php } ?>
        <?php } else { ?>

            <div class="text-center">
                <h4>Сообщений не существует!</h4>
            </div>
        <?php } ?>

        <!-- pagination -->
        <nav>
            <ul class="pagination">

                <?php if ($pages['first'] != null) { ?>
                    <li><a href="/post/page=<?php echo $pages['first'] ?>">Первая</a></li>
                <?php } ?>

                <?php if ($pages['pre'] != null) { ?>
                    <li><a href="<?php echo $link . $pages['pre'] ?>"><?php echo $pages['pre'] ?></a></li>
                <?php } ?>

                <?php if ($pages['cur'] != null) { ?>
                    <li><a class="active btn-primary"
                           href="<?php echo $link . $pages['cur'] ?>"><?php echo $pages['cur'] ?></a></li>
                <?php } ?>

                <?php if ($pages['next'] != null) { ?>
                    <li><a href="<?php echo $link . $pages['next'] ?>"><?php echo $pages['next'] ?></a></li>
                <?php } ?>

                <?php if ($pages['last'] != null) { ?>
                    <li><a href="<?php echo $link . $pages['last'] ?>">Последняя</a></li>
                <?php } ?>


            </ul>
        </nav>


    </div>
    <!-- left menu -->
    <?php if (isset($regions) or isset($lastComment)) { ?>
        <div class="col-md-4">
            <?php if (isset($regions)) { ?>
                <div class="list-group">
                    <h2> Список регионов</h2>
                    <?php foreach ($regions as $region) { ?>
                        <a href="/region=<?php echo $region['id'] ?>"
                           class="list-group-item"><?php echo $region['name'] ?></a>
                    <?php } ?>
                </div>
            <?php } ?>
            <?php if (isset($lastComment)) { ?>
                <div class="list-group">
                    <h2> Последние комментарии</h2>
                    <?php foreach ($lastComment as $item) { ?>
                        <div class="list-group">
                            <a href="/post/<?php echo $item['post']['id'] ?>"
                               class="list-group-item"><?php echo $item['post']['name'] ?> <br><br>
                             Комментарий:   <?php echo $item['content'] ?> <br>
                              Дата добавления:  <?php echo $item['time'] ?>
                            </a>

                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    <?php } ?>


</div>


</body>
</html>