<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
</head>
<body>

<!-- javascript -->

<script>
    var a;
    $(document).ready(function(){
        $("#content1").mouseenter(function(){
          a = $('#price').html();
            $('#price').text(a - a*0.1);
            $('#price').attr('color', 'red');
            $('#price').attr('font-size', '44px');

        });
    });
</script>

<!-- post -->
<div class=" center-block text-center">
    <div class="col-md-8">
        <?php if (!empty($posts)) { ?>
            <!-- reklama -->
            <?php if (!empty($reklams)) {
                $reklam = array_shift($reklams); ?>

                <div class="thumbnail" id="content1"  style="background-color: yellow">
                    <h1 id="main1" style="background-color: red">ТОП ОБЬЯВЛЕНИЕ</h1>
                        <h3><b><?php echo $reklam['name'] ?></b> <?php echo $reklam['company'] ?></h3>
                        <h4>Всего лишь <b style="" id="price"><?php echo $reklam['price'] ?></b> грн.</h4>
                    <a href="/reklam/<?php echo $reklam['id'] ?>">Перейти на сайт рекламодателя</a>
                </div>

            <?php } ?>


            <?php foreach ($posts as $post) { ?>
                <div class="thumbnail">
                    <h3> <?php echo $post['name'] ?></h3>


                    <div class="row table">
                        <div class="col-sm-6 col-md-6">
                            <a href="/region=<?php echo $post['region']['id'] ?>">
                                <h3>
                                    <?php echo $post['region']['name'] ?>
                                </h3></a>

                            <a href="/category=<?php echo $post['category']['id'] ?>">
                                <h3>
                                    <?php echo $post['category']['name'] ?>
                                </h3></a>
                            <h4>Автор: <a
                                    href="/post/user=<?php echo $post['author']['id'] ?>"><?php echo $post['author']['login'] ?> </a>
                            </h4>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <a href="#"><h3>Комментариев<span class="badge"><?php echo $post['commentCnt'] ?></span>
                                </h3></a>
                            <h6> Дата добавления: <?php echo $post['created'] ?></h6>

                        </div>
                    </div>


                    <img src="/images/<?php echo $post['image'] ?>" alt="131">
                    <div class="caption">

                        <p> <?php echo substr($post['content'], 0, 325) . "..." ?></p>
                        <?php if ($post['category']['name'] == "Аналитика" and !isset($_SESSION['user'])){ ?>
                            <br>
                            <h5>Вы не можете читать эту новость, так вы не зарегистрованный пользователь!</h5><br>
                            <h5>Пожалуйста,
                                <h3><a href="/register">Зарегиструйтесь</a></h3>
                                или
                                <h3><a href="/login">Авторизуйтесь</a></h3>
                            </h5>
                        <?php }else { ?>
                        <p><a href="/post/<?php echo $post['id'] ?>" class="btn btn-primary" role="button">Читать
                                полностью</a>
                            <?php } ?>
                            <?php if (isset($_SESSION['user']) and $_SESSION['user']['isAdmin'] == 1){ ?>
                        <p><a href="/admin/deletePost/post=<?php echo $post['id'] ?>" class="btn btn-primary"
                              role="button">Удалить пост</a>

                        <p><a href="/admin/editPost/post=<?php echo $post['id'] ?>" class="btn btn-primary"
                              role="button">Редактировать пост</a>
                            <?php } ?>
                    </div>
                </div>

                <!-- reklama -->
                <?php if (!empty($reklams)) {
                    $reklamID = array_rand($reklams);
                    $reklam = $reklams[$reklamID];
                    unset($reklams[$reklamID]);
                    ?>
                    <div id="content1" class="thumbnail" style="background-color: yellow">
                        <h3><b><?php echo $reklam['name'] ?></b> <?php echo $reklam['company'] ?></h3>
                        <h4>Цена: <?php echo $reklam['price'] ?> грн.</h4>
                        <a href="/reklam/<?php echo $reklam['id'] ?>">Перейти на сайт рекламодателя</a>
                    </div>
                <?php } ?>


            <?php } ?>
        <?php } else { ?>

            <div class="text-center">
                <h4>Сообщений не существует!</h4>
            </div>
        <?php } ?>

        <!-- pagination -->
        <nav>
            <ul class="pagination">

                <?php if ($pages['first'] != null) { ?>
                    <li><a href="/post/page=<?php echo $pages['first'] ?>">Первая</a></li>
                <?php } ?>

                <?php if ($pages['pre'] != null) { ?>
                    <li><a href="<?php echo $link . $pages['pre'] ?>"><?php echo $pages['pre'] ?></a></li>
                <?php } ?>

                <?php if ($pages['cur'] != null) { ?>
                    <li><a class="active btn-primary"
                           href="<?php echo $link . $pages['cur'] ?>"><?php echo $pages['cur'] ?></a></li>
                <?php } ?>

                <?php if ($pages['next'] != null) { ?>
                    <li><a href="<?php echo $link . $pages['next'] ?>"><?php echo $pages['next'] ?></a></li>
                <?php } ?>

                <?php if ($pages['last'] != null) { ?>
                    <li><a href="<?php echo $link . $pages['last'] ?>">Последняя</a></li>
                <?php } ?>


            </ul>
        </nav>


    </div>
    <!-- left menu -->
    <?php if (isset($regions) or isset($lastComment)) { ?>
        <div class="col-md-4">
            <?php if (isset($regions)) { ?>
                <div class="list-group">
                    <h2> Список регионов</h2>
                    <?php foreach ($regions as $region) { ?>
                        <a href="/region=<?php echo $region['id'] ?>"
                           class="list-group-item btn-success"><?php echo $region['name'] ?></a>
                    <?php } ?>
                </div>
            <?php } ?>


            <?php if (isset($categories)) { ?>
                <div class="list-group">
                    <h2> Список категорий</h2>
                    <?php foreach ($categories as $category) { ?>
                        <a href="/category=<?php echo $category['id'] ?>"
                           class="list-group-item btn-success"><?php echo $category['name'] ?></a>
                        <?php if (is_array($category['posts'])) { ?>
                            <?php foreach ($category['posts'] as $post) { ?>
                                <a href="/post/<?php echo $post['id'] ?>"
                                   class="list-group-item btn-info"><?php echo $post['name'] ?></a>
                            <?php } ?>

                        <?php } ?>
                    <?php } ?>
                </div>

            <?php } ?>

            <?php if (isset($ActivePosts)) { ?>
                <div class="list-group">
                    <h2> Самые активные темы за сутки</h2>
                    <?php foreach ($ActivePosts as $ActivePost) { ?>
                        <a href="/post/<?php echo $ActivePost['id'] ?>"
                           class="list-group-item btn-success"><?php echo $ActivePost['name'] ?></a>
                    <?php } ?>
                </div>

            <?php } ?>

            <?php if (isset($topCommentators)) { ?>
                <div class="list-group">
                    <h2> Топ 5 комментаторов нашего портала</h2>
                    <?php foreach ($topCommentators as $topCommentator) { ?>
                        <a href="/comment/user=<?php echo $topCommentator['author']['id'] ?>"
                           class="list-group-item btn-warning"><?php echo $topCommentator['author']['login'] ?>
                            (Комментариев: <?php echo $topCommentator['cnt'] ?> )</a>
                    <?php } ?>
                </div>

            <?php } ?>




            <?php if (isset($lastComment)) { ?>
                <div class="list-group">
                    <h2> Последние комментарии</h2>
                    <?php foreach ($lastComment as $item) { ?>
                        <div class="list-group">
                            <a href="/post/<?php echo $item['post']['id'] ?>"
                               class="list-group-item"><?php echo $item['post']['name'] ?> <br><br>
                                Комментарий: <?php echo substr($item['content'], 0, 200) ?>... <br>
                                Дата добавления: <?php echo $item['time'] ?>
                            </a>

                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    <?php } ?>


</div>


</body>
</html>