<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php $title ?></title>
</head>
<body>

<form method="POST" class="form-horizontal" name="search" action="/search">
    <div class="text-center">
        <h4>
            <a class="btn-success" href="/close/search">Сбросить фильтр</a>
        </h4>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Автор:</label>
        <div class="col-sm-5">
            <input name="author" type="text" class="form-control" placeholder="Автор"
                   value="<?php if (isset($_POST['author'])) echo $_POST['author']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">От какого(Год-Месяц-День):</label>
        <div class="col-sm-5">
            <input name="timeStart" type="text" class="form-control" placeholder="От"
                   value="<?php if (isset($_POST['timeStart'])) echo $_POST['timeStart']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">До какого(Год-Месяц-День:</label>
        <div class="col-sm-5">
            <input name="timeEnd" type="text" class="form-control" placeholder="До"
                   value="<?php if (isset($_POST['timeEnd'])) echo $_POST['timeEnd']; ?>">
        </div>
    </div>

    <div id="reg" class=" form-group center-block col-sm-5">
        <select class="form-control" size="5" name="region">
            <option disabled>Выберите регион:</option>
            <?php foreach ($regions as $region) { ?>
                <option value="<?php echo $region['id'] ?>"><?php echo $region['name'] ?></option>
            <?php } ?>
        </select>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-info">Поиск</button>
        </div>
    </div>
</form>

<div class="text-center">
    <div class=" center-block text-center">
        <div class="col-md-8">
            <?php if (!empty($posts)) { ?>
                <!-- reklama -->
            <?php if (!empty($reklams)) {
                    $reklam = array_shift($reklams); ?>
                    <div class="thumbnail" style="background-color: yellow">
                        <h1 style="background-color: red">ТОП ОБЬЯВЛЕНИЕ</h1>
                        <h3><b><?php echo $reklam['name'] ?></b> <?php echo $reklam['company'] ?></h3>
                        <h4>Цена: <?php echo $reklam['price'] ?> грн.</h4>
                        <a href="/reklam/<?php echo $reklam['id'] ?>">Перейти на сайт рекламодателя</a>
                    </div>
                <?php } ?>

             <?php   foreach ($posts as $post) { ?>
                    <div class="thumbnail">
                        <h3> <?php echo $post['name'] ?></h3>


                        <div class="row table">
                            <div class="col-sm-6 col-md-6">
                                <a href="/region=<?php echo $post['region']['id'] ?>">
                                    <h3><?php echo $post['region']['name'] ?></h3></a>
                                <h4>Автор: <a
                                        href="/post/user=<?php echo $post['author']['id'] ?>"><?php echo $post['author']['login'] ?> </a>
                                </h4>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <a href="#"><h3>Комментариев<span
                                            class="badge"><?php echo $post['commentCnt'] ?></span></h3></a>
                                <h6> Дата добавления: <?php echo $post['created'] ?></h6>

                            </div>
                        </div>


                        <img src="../images/<?php echo $post['image'] ?>" alt="131">
                        <div class="caption">

                            <p> <?php echo substr($post['content'], 0, 325) . "..." ?></p>
                            <p><a href="/post/<?php echo $post['id'] ?>" class="btn btn-primary" role="button">Читать
                                    полностью</a>
                        </div>
                    </div>

                    <!-- reklama -->
                    <?php if (!empty($reklams)) {
                        $reklamID = array_rand($reklams);
                        $reklam = $reklams[$reklamID];
                        unset($reklams[$reklamID]);
                        ?>
                        <div class="thumbnail" style="background-color: yellow">
                            <h3><b><?php echo $reklam['name'] ?></b> <?php echo $reklam['company'] ?></h3>
                            <h4>Цена: <?php echo $reklam['price'] ?> грн.</h4>
                            <a href="/reklam/<?php echo $reklam['id'] ?>">Перейти на сайт рекламодателя</a>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } else { ?>

                <div class="text-center">
                    <h4>Сообщений не существует!</h4>
                </div>
            <?php } ?>

            <nav>
                <ul class="pagination">

                    <?php if ($pages['first'] != null) { ?>
                        <li><a href="<?php echo $link . $pages['first'] ?>">Первая</a></li>
                    <?php } ?>

                    <?php if ($pages['pre'] != null) { ?>
                        <li><a href="<?php echo $link . $pages['pre'] ?>"><?php echo $pages['pre'] ?></a></li>
                    <?php } ?>

                    <?php if ($pages['cur'] != null) { ?>
                        <li><a class="active btn-primary"
                               href="<?php echo $link . $pages['cur'] ?>"><?php echo $pages['cur'] ?></a></li>
                    <?php } ?>

                    <?php if ($pages['next'] != null) { ?>
                        <li><a href="<?php echo $link . $pages['next'] ?>"><?php echo $pages['next'] ?></a></li>
                    <?php } ?>

                    <?php if ($pages['last'] != null) { ?>
                        <li><a href="<?php echo $link . $pages['last'] ?>">Последняя</a></li>
                    <?php } ?>


                </ul>
            </nav>
        </div>


</body>
</html>